name: Auto Release Lucky

on:
  push:
    paths:
      - 'dist/**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Extract version
      id: extract
      run: |
        # 找出第一个 dist 目录下的文件名
        FILE=$(ls dist | head -n 1)
        echo "Found file: $FILE"

        # 提取版本号
        VERSION_TAG=$(echo "$FILE" | grep -oE 'lucky_[0-9]+\.[0-9]+\.[0-9]+')
        echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV
        echo "version=$VERSION_TAG" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.VERSION_TAG }}
        name: ${{ env.VERSION_TAG }}
        files: dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
